### save short
POST http://localhost:5000/api/shorts
Content-Type: application/json

{
  "title": "Heaven Nature",
  "videoUrl": "https://cdn.pixabay.com/video/2025/10/31/313145_large.mp4",
  "tags": ["nature", "outdoor", "heaven"]
}


### get all shorts
GET http://localhost:5000/api/shorts

### get short by id
GET http://localhost:5000/api/shorts/1